[package]
name = "rustkat"
version = "0.1.0"
edition = "2021"
authors = ["blikq https://github.com/blikq blikqmain@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
